#!/bin/bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

ERDO_DIR=`dirname $0`/../../..

java -ea -Dpid=$$ -Djava.util.logging.config.file=$ERDO_DIR/src/main/resources/logging.properties -Dfile.encoding=UTF-8 -classpath $CLASSPATH com.geophile.erdo.utilities.ConsolidateAll $*
